domain: example.com
url: https://example.com
baseurl: 

title: Archival Poetry
email: 
author: Roberto Vargas

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
